language: cpp
os:
    - osx
    - linux
compiler:
    - clang
notifications:
    email: false
env:
    matrix:
        - JULIAVERSION="nightlies"
before_install:
    - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then source ./CI/install_julia_osx.sh; fi
    - if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then source ./CI/install_julia_linux.sh; fi
    - if [[ -a .git/shallow ]]; then git fetch --unshallow; fi
script:
    - julia -e 'Pkg.init(); run(`ln -s $(pwd()) $(Pkg.dir("Nettle"))`); Pkg.pin("Nettle"); Pkg.resolve(); Pkg.build("Nettle")'
    - julia ./test/test.jl
